"""
tests/test_header_detection.py
Tests for the auto-header-row detector in skills/load_data.py.

Covers the failure mode the user reported: a workbook whose first row is
a title like "Identified Proteins (1919)" and whose real column headers
are in row 1.
"""
from __future__ import annotations

import pandas as pd
import pytest

from skills.load_data import _detect_header_row


# ── Normal cases (header in row 0 — must NOT shift it) ───────────────────────

class TestNormalHeader:

    def test_real_header_in_row_zero(self):
        # Row 0 has real headers; no title above.
        raw = pd.DataFrame([
            ["Protein Name", "Accession Number", "A SpC", "B SpC"],
            ["Myosin",       "Q5SX39",            12,      10],
            ["Albumin",      "P02769",             5,       7],
        ])
        assert _detect_header_row(raw) == 0

    def test_pure_numeric_data_falls_back_to_zero(self):
        # No header-like tokens anywhere → default 0
        raw = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
        assert _detect_header_row(raw) == 0


# ── Title-row cases (the actual bug) ─────────────────────────────────────────

class TestTitleRowAboveHeader:

    def test_identified_proteins_title_skipped(self):
        # Row 0: title with row count; row 1: real headers
        raw = pd.DataFrame([
            ["Identified Proteins (1919)", None, None, None, None],
            ["Protein Name", "Accession Number", "Molecular Weight",
             "A SpC", "B SpC"],
            ["Myosin",       "Q5SX39",            223.0, 12, 10],
            ["Albumin",      "P02769",            66.5,   5,  7],
        ])
        assert _detect_header_row(raw) == 1

    def test_multiple_title_rows_above_header(self):
        raw = pd.DataFrame([
            ["Dataset: experimental cohort 2024",  None, None, None],
            ["Generated by MaxQuant 2.0",          None, None, None],
            ["Protein IDs", "Gene names", "LFQ Intensity A", "LFQ Intensity B"],
            ["P1",          "GENE_A",     1.0e9,             9.0e8],
            ["P2",          "GENE_B",     5.0e8,             4.0e8],
        ])
        assert _detect_header_row(raw) == 2

    def test_lfq_intensity_headers_detected(self):
        # MaxQuant-style headers
        raw = pd.DataFrame([
            ["proteinGroups.txt — exported 2024-01"],
            ["Protein IDs", "Gene names",
             "LFQ intensity Sample_1", "LFQ intensity Sample_2", "iBAQ Sample_1"],
            ["P1", "G1", 1.0, 2.0, 0.5],
        ])
        assert _detect_header_row(raw) == 1

    def test_olink_npx_headers_detected(self):
        raw = pd.DataFrame([
            ["Olink NPX Manager — Cohort A"],
            ["Sample ID", "Assay", "Panel", "NPX value"],
            ["S001",      "IL6",   "Inflammation", 4.2],
        ])
        assert _detect_header_row(raw) == 1


# ── Edge cases ───────────────────────────────────────────────────────────────

class TestEdgeCases:

    def test_empty_dataframe_returns_zero(self):
        assert _detect_header_row(pd.DataFrame()) == 0

    def test_single_row_returns_zero(self):
        raw = pd.DataFrame([["Protein Name", "Accession"]])
        assert _detect_header_row(raw) == 0

    def test_header_with_max_scan_cap(self):
        # If the real header is past max_scan, the detector won't find it.
        rows = [["padding"] * 5 for _ in range(15)]
        rows[13] = ["Protein Name", "Accession", "Intensity", "SpC", "MW"]
        raw = pd.DataFrame(rows)
        # With default max_scan=12, row 13 is unreachable → falls back to 0
        assert _detect_header_row(raw, max_scan=12) == 0
        # Bump scan window and it should find row 13
        assert _detect_header_row(raw, max_scan=14) == 13

    def test_title_with_one_cell_doesnt_win(self):
        # A title with one cell containing "Protein" must NOT beat a real
        # header row even though "protein" is a token match — min_non_empty=2
        raw = pd.DataFrame([
            ["Protein quantification report",   None, None, None],
            ["Accession", "Gene", "Intensity",  "MW"],
            ["P1",        "G1",   1.0,          50.0],
        ])
        # Row 1 has 4 non-empty + 4 token matches → wins
        # Row 0 has 1 non-empty → below min_non_empty=2, not counted
        assert _detect_header_row(raw) == 1
