"""
agents/ingestion_agent.py
Data Layer — IngestionAgent

Loads and validates the uploaded proteomics file, surfaces dataset metadata
in BiomarkerState, and auto-routes pooled designs to PooledFoldChangeSkill.

Every user-facing message is generated by the LLM so responses are
contextual and data-aware rather than generic templates.
"""
from __future__ import annotations

import json
import logging
import os
import re
from pathlib import Path
from typing import Dict, List

from agents.base_agent import BaseAgent
from config.settings import get_settings
from core.state import BiomarkerState
from core.tracing import get_ingestion_metadata
from skills.load_data import DataLoadingSkill

logger   = logging.getLogger(__name__)
settings = get_settings()

# ── LangSmith @traceable (graceful no-op if not installed) ───────────────────
try:
    from langsmith import traceable as _traceable
    from langsmith.run_helpers import get_current_run_tree as _get_run_tree
except ImportError:
    def _traceable(**_kw):          # type: ignore[misc]
        def _wrap(fn): return fn
        return _wrap
    def _get_run_tree():            # type: ignore[misc]
        return None

PROCESSED_DIR = Path("data/processed")
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

_GROUP_INFERENCE_PROMPT = """\
You are a bioinformatics data analyst.
Below are sample column names from a proteomics dataset.
Identify biological groups by looking for common naming patterns:
  - Explicit group names (WT, KO, Disease, Control, mdx, uDys5, etc.)
  - Numeric suffixes indicating replicates (_1, _2, _3 or .1 .2 .3)
  - Common prefixes or shared substrings

Return a JSON object mapping group name → list of column names.
Example: {"WT": ["WT_1","WT_2","WT_3"], "KO": ["KO_1","KO_2","KO_3"]}
If you cannot detect groups, return {}.
Output ONLY the JSON object, nothing else.
"""


class IngestionAgent(BaseAgent):
    """
    Data Layer — ingests CSV / Excel, normalises orientation, detects data type,
    auto-detects groups, and surfaces all metadata in state.

    Every user-facing message is produced by an LLM call so the response is
    always tailored to what was actually found in the file.

    Auto-routing
    ------------
    When the loader detects a MaxQuant-style multi-sheet Excel file it sets
    ``is_pooled_design=True`` and provides a ``label_map``.  This agent
    propagates both to state and sets ``omic_type="proteomics_pooled"`` so
    BiomarkerAgent dispatches PooledFoldChangeSkill without manual group
    assignment.
    """

    def __init__(self) -> None:
        super().__init__(
            deployment_name=settings.azure_deployment_ingestion,
            system_prompt_path="prompts/ingestion_agent.txt",
        )
        self.loader = DataLoadingSkill()

    # ── Main entry point ──────────────────────────────────────────────────────

    @_traceable(run_type="chain", name="agent.ingestion",
                tags=["biomarker-discovery", "ingestion"])
    def run(self, state: BiomarkerState) -> BiomarkerState:
        rt = _get_run_tree()
        if rt is not None:
            try:
                rt.extra.setdefault("metadata", {}).update(get_ingestion_metadata(state))
            except Exception:
                pass
        data_path   = state.get("data_path")
        data_format = state.get("data_format", "csv")

        # ── Guard: skip re-ingestion if data already loaded ──────────────────
        if state.get("data_type") and state.get("n_proteins"):
            logger.info("IngestionAgent: data already loaded (%s), skipping.", state["data_type"])
            msg = self._llm_already_loaded(state)
            state["messages"].append({"role": "assistant", "content": msg})
            return state

        # ── Guard: file must exist ────────────────────────────────────────────
        if not data_path or not os.path.exists(data_path):
            logger.warning("IngestionAgent: no file at '%s'", data_path)
            state["status"]        = "error"
            state["error_message"] = "No data file found."
            msg = self._llm_error("No data file was found. Please upload a CSV or Excel proteomics file.")
            state["messages"].append({"role": "assistant", "content": msg})
            return state

        state["raw_data_path"] = data_path
        logger.info("IngestionAgent: loading '%s' (format=%s)", data_path, data_format)

        # ── Load ──────────────────────────────────────────────────────────────
        try:
            result = self.loader.execute(
                data_path=data_path,
                data_format=data_format,
                output_dir=str(PROCESSED_DIR),
            )
        except Exception as exc:
            logger.error("DataLoadingSkill failed: %s", exc, exc_info=True)
            state["status"]        = "error"
            state["error_message"] = str(exc)
            msg = self._llm_error(f"Data loading failed: {exc}")
            state["messages"].append({"role": "assistant", "content": msg})
            return state

        # ── Propagate to state ────────────────────────────────────────────────
        state["data_path"]        = result["processed_path"]
        state["data_type"]        = result["data_type"]
        state["data_format"]      = result["data_format"]
        state["n_proteins"]       = result["n_proteins"]
        state["n_samples"]        = result["n_samples"]
        state["sample_columns"]   = result["sample_columns"]
        state["metadata_columns"] = result["metadata_columns"]
        state["is_pooled_design"] = result.get("is_pooled_design", False)
        state["status"]           = "data_loaded"

        is_pooled       = result.get("is_pooled_design", False)
        label_map       = result.get("label_map")
        identifier_info = result.get("identifier_info")
        all_sheets      = result.get("all_sheets", {})

        if label_map:
            state["label_map"] = label_map
        if identifier_info is not None:
            state["identifier_info"] = identifier_info
        if all_sheets:
            state["all_sheets"] = all_sheets

        # ── TMT batch structure ───────────────────────────────────────────────
        tmt_batches = result.get("tmt_batches")
        if tmt_batches:
            state["tmt_batches"] = tmt_batches
            logger.info("TMT multi-batch structure stored: %s", list(tmt_batches.keys()))

        # ── omic_type routing ─────────────────────────────────────────────────
        if is_pooled:
            state["omic_type"] = "proteomics_pooled"
            logger.info("Pooled design — omic_type='proteomics_pooled'. Label map: %s", label_map)
        elif result.get("omic_type"):
            # DataLoadingSkill may hint the omic type (e.g. "proteomics_silac")
            state["omic_type"] = result["omic_type"]
            logger.info("omic_type set from DataLoadingSkill hint: '%s'", result["omic_type"])

        # ── Auto-detect groups from column names (non-pooled) ─────────────────
        inferred_groups: Dict[str, List[str]] = {}
        if not is_pooled and result["sample_columns"]:
            inferred_groups = self._infer_groups(result["sample_columns"])
            if len(inferred_groups) >= 2:
                group_names = list(inferred_groups.keys())
                state["group1_label"]   = group_names[0]
                state["group1_samples"] = inferred_groups[group_names[0]]
                state["group2_label"]   = group_names[1]
                state["group2_samples"] = inferred_groups[group_names[1]]
                logger.info("Auto-detected groups: %s", {k: len(v) for k, v in inferred_groups.items()})

        # ── LLM message ────────────────────────────────────────────────────────
        msg = self._llm_load_message(result, is_pooled, label_map, inferred_groups)
        state["messages"].append({"role": "assistant", "content": msg})

        logger.info(
            "IngestionAgent done: %d proteins, %d samples, pooled=%s, groups=%s",
            result["n_proteins"], result["n_samples"], is_pooled,
            list(inferred_groups.keys()) if inferred_groups else label_map,
        )

        # Update span metadata with post-load values
        rt = _get_run_tree()
        if rt is not None:
            try:
                rt.extra.setdefault("metadata", {}).update(
                    get_ingestion_metadata(state, result)
                )
            except Exception:
                pass

        return state

    # ── Group inference ───────────────────────────────────────────────────────

    @_traceable(run_type="chain", name="ingestion.group_inference",
                tags=["biomarker-discovery", "ingestion"])
    def _infer_groups(self, sample_columns: List[str]) -> Dict[str, List[str]]:
        prompt = _GROUP_INFERENCE_PROMPT + f"\nColumn names:\n{sample_columns}"
        messages = [
            {"role": "system", "content": "You are a bioinformatics data analyst."},
            {"role": "user",   "content": prompt},
        ]
        try:
            raw = self._call_llm(messages, max_tokens=400, temperature=0.0).strip()
            raw = re.sub(r"^```(?:json)?\s*|\s*```$", "", raw, flags=re.MULTILINE).strip()
            groups = json.loads(raw)
            if isinstance(groups, dict) and groups:
                return groups
        except Exception as exc:
            logger.warning("Group inference in IngestionAgent failed: %s", exc)
        return {}

    # ── LLM message builders ──────────────────────────────────────────────────

    def _llm_load_message(
        self,
        result: dict,
        is_pooled: bool,
        label_map: dict | None,
        inferred_groups: Dict[str, List[str]],
    ) -> str:
        sample_preview = result["sample_columns"][:10]
        meta_cols      = result["metadata_columns"][:6]

        ctx  = f"DATA LOADED SUCCESSFULLY\n\n"
        ctx += f"n_proteins: {result['n_proteins']}\n"
        ctx += f"n_samples: {result['n_samples']}\n"
        ctx += f"data_type: {result['data_type']}\n"
        ctx += f"is_pooled_design: {is_pooled}\n"
        ctx += f"sample_columns (first 10): {sample_preview}\n"
        ctx += f"metadata_columns: {meta_cols}\n"
        if label_map:
            ctx += f"label_map (pooled groups): {label_map}\n"
        if inferred_groups:
            ctx += f"inferred_groups: {{{', '.join(f'{k}: {len(v)} samples' for k, v in inferred_groups.items())}}}\n"
        else:
            ctx += "inferred_groups: none detected\n"

        messages = [
            {"role": "system", "content": self.system_prompt},
            {"role": "user",   "content": ctx},
        ]
        try:
            return self._call_llm(messages, max_tokens=350)
        except Exception as exc:
            logger.warning("IngestionAgent LLM message failed: %s — using fallback.", exc)
            return self._fallback_load_message(result, is_pooled, label_map, inferred_groups)

    def _llm_already_loaded(self, state: BiomarkerState) -> str:
        ctx = (
            f"Data is already loaded in this session:\n"
            f"- {state['n_proteins']} proteins\n"
            f"- {state['n_samples']} samples\n"
            f"- Data type: {state.get('data_type', 'unknown')}\n"
            f"- Analysis status: {state.get('status', 'ready')}\n"
            "Tell the user data is already loaded and suggest what they can do next "
            "(run analysis, view results, enrich pathways, etc.)."
        )
        messages = [
            {"role": "system", "content": self.system_prompt},
            {"role": "user",   "content": ctx},
        ]
        try:
            return self._call_llm(messages, max_tokens=150)
        except Exception:
            return (
                f"Data already loaded — **{state['n_proteins']} proteins**, "
                f"**{state['n_samples']} samples** ({state.get('data_type', '')}). "
                "Ready for analysis."
            )

    def _llm_error(self, error_text: str) -> str:
        messages = [
            {"role": "system", "content": self.system_prompt},
            {"role": "user",   "content": f"ERROR: {error_text}\nTell the user what went wrong and how to fix it."},
        ]
        try:
            return self._call_llm(messages, max_tokens=150)
        except Exception:
            return error_text

    # ── Fallback (no LLM) ─────────────────────────────────────────────────────

    @staticmethod
    def _fallback_load_message(
        result: dict,
        is_pooled: bool,
        label_map: dict | None,
        inferred_groups: Dict[str, List[str]],
    ) -> str:
        lines = [
            "### Data Loaded\n",
            f"- **{result['n_proteins']}** proteins · **{result['n_samples']}** samples",
            f"- Data type: **{result['data_type']}**",
        ]
        if is_pooled and label_map:
            groups_str = ", ".join(f"{k}→{v}" for k, v in label_map.items())
            lines += [f"- Pooled design: {groups_str}", "\n**Ready for fold-change analysis.**"]
        elif inferred_groups:
            g = list(inferred_groups.keys())
            lines += [f"- Groups detected: {', '.join(g)}", "\n**Ready for analysis.**"]
        else:
            lines.append("\nTell me which groups to compare, e.g. *'compare Control vs Disease'*, then I'll run the analysis.")
        return "\n".join(lines)
